---
fs3combat:
  achievements:
    fs3_hero:
      type: fs3
      message: Heroed from a knockout.
    fs3_joined_combat:
      type: fs3
      message: Joined %{count} combats.
  allow_mounts: true
  allow_vehicles: true
  combatant_types:
    Observer:
      hitloc: Humanoid
    Soldier:
      weapon: Rifle
      weapon_specials:
      - Ap
      armor: Tactical
      hitloc: Humanoid
      defense_skill: Reflexes
    Unarmed:
      weapon: Unarmed
      hitloc: Humanoid
      defense_skill: Reflexes
    Centurion:
      weapon: LMG
      weapon_specials:
      - Bipod
      armor: Centurion
      hitloc: Humanoid
      defense_skill: Reflexes
    Aa:
      weapon: Missile
      armor: Aa Battery
      vehicle: Aa Battery
      hitloc: Tank
      defense_skill: Reflexes
    Cylon:
      weapon: Pistol
      armor: Cylon
      hitloc: Humanoid
      defense_skill: Reflexes
    Viper:
      vehicle: Viper
      hitloc: Humanoid
      defense_skill: Piloting
    Raptor:
      vehicle: Raptor
      hitloc: Humanoid
      defense_skill: Piloting
    Raider:
      vehicle: Raider
      hitloc: Humanoid
      defense_skill: Piloting
    Heavy:
      vehicle: Heavy Raider
      hitloc: Humanoid
      defense_skill: Piloting
    Target:
      hitloc: Target
      weapon: Unarmed
    Tank:
      weapon: Cannon
      armor: Tank
      vehicle: Tank
      hitloc: Tank
      defense_skill: Driving
    Apc:
      weapon: HMG
      armor: Apc
      vehicle: Tank
      hitloc: Tank
      defense_skill: Driving
    Truck:
      weapon: Unarmed
      armor: Truck
      vehicle: Truck
      hitloc: Truck
      defense_skill: Driving
    Predator:
      vehicle: Predator
      hitloc: Fighter
      defense_skill: Piloting
    Rhino:
      vehicle: Rhino
      hitloc: Transport
      defense_skill: Piloting
    Carballa:
      weapon: 120mm Main
      armor: Carballa
      vehicle: Carballa
      hitloc: Tank
      defense_skill: Driving
    Rapier:
      weapon: 30mm HVC
      armor: Apc
      vehicle: Rapier
      hitloc: Tank
      defense_skill: Driving
    Samnite:
      weapon: 20mm CG
      armor: Apc
      vehicle: Samnite
      hitloc: Tank
      defense_skill: Driving
  default_type: Soldier
  shortcuts:
    combat/skill: combat/summary
    combat/skills: combat/summary
    combat/slackers: combat/summary
    combat/add: combat/join
    combat/remove: combat/leave
    combat/hitlocs: combat/hitloc
    vehicles: vehicle
    healing: heal/list
    weapons: weapon
    mounts: mount
  stances:
    Aggressive:
      attack_mod: 2
      defense_mod: -2
    Reckless:
      attack_mod: 4
      defense_mod: -4
    Normal:
      attack_mod: 0
      defense_mod: 0
    Defensive:
      attack_mod: -2
      defense_mod: 2
    Evasive:
      attack_mod: -4
      defense_mod: 4
    Cover:
      attack_mod: -1
      defense_mod: 1
    Hidden:
      attack_mod: 0
      defense_mod: 0
