---
fs3skills:
  action_skills:
  - name: Alertness
    desc: Noticing things and being aware of the surroundings.
    linked_attr: Perception
    specialties:
    - Visual Space
    - Visual Ground
    - Visual Ship
    - Auditory Ground
    - Auditory Ship
  - name: Composure
    desc: Coolness under pressure.
    linked_attr: Grit
    specialties:
    - Social Pressure
    - Torture Resistance
    - Work Pressure
  - name: Athletics
    desc: General running, jumping, climbing, etc.
    linked_attr: Reflexes
    specialties:
    - Pyramid
    - Kasta
    - Climbing
  - name: Throw
    desc: Use this for grenade and general throwing activities.
    linked_attr: Reflexes
    specialties:
    - Grenade
    - Kasta Disk
    - Pyramid Ball
  - name: Stealth
    desc: Being physically sneaky.
    linked_attr: Reflexes
  - name: Subterfuge
    desc: Performing acts of subterfuge.  Spy stuff that doesn't include Stealth.
    linked_attr: Wits
  - name: Piloting
    desc: Flying air and spacecraft.  Characters are not allowed to cross-train at
      this time.  Search and Rescue is restricted.
    linked_attr: Reflexes
    specialties:
    - Viper
    - Raptor
    - Predator
    - Rhino
    - Search And Rescue
    - Freighter
    - Shuttle
    - Corvette
    - Capital
  - name: ECM
    desc: Electronic countermeasures officers have these.  ECO anyone?
    linked_attr: Wits
  - name: Hand To Hand
    desc: Fighting with hands, feet, and just about anything else related to the body.
    linked_attr: Reflexes
  - name: Sm Weapons
    desc: "(Small Weapons) daggers, shivs, brass knuckles, a rock, and other found
      objects."
    linked_attr: Reflexes
    specialties:
    - Baton
    - Found Object
    - Knife
    - Improvised Weapons
  - name: Prim Weapons
    desc: "(Primitive Weapons) swords, staffs, bayonets, spears, etc."
    linked_attr: Reflexes
    specialties:
    - Broadsword
    - Epee
    - Foil
    - Sabre
    - Rapier
    - Cutlass
    - Short Sword
    - Bayonette
    - Spear Or Harpoon
    - Staff
    - Cane
    - Branch
    - Recurve Bow
    - Longbow
    - Compound Bow
    - Crossbow
    - Whip
  - name: Driving
    desc: Driving things, all kinds of things.
    linked_attr: Grit
    specialties:
    - Trucks
    - Motorcycles
    - Armored Vehicles
    - Motorboats
    - Sailing
  - name: Firearms
    desc: Shooting guns.
    linked_attr: Reflexes
    specialties:
    - Handgun Or Sidearm
    - Shotgun
    - Battle Rifle
    - Marksman Rifle
    - Hunting Rifle
  - name: Gunnery
    desc: Vehicle/special weapons (cannons, launchers, turrets).
    linked_attr: Brawn
    specialties:
    - Dogfighting
    - Wing Weapons Wystems
    - Turret Or Door Gun
    - Artillery
    - Armored Vehicle
    - Tank
    - Machine Gun
    - Grenade Launcher
    - Heavy weapon
  - name: Demolitions
    desc: |-
      This is a restricted skill.  For throwing grenades, see the Throwing
      skill.

      Everyone but Combat Engineers, SF, and EODs must set this skill to
      0/Incapable. To find details on skill limitations for Combat Engineers,
      SF, and EODs, see

      http://www.so-say-we-all.com/wiki/cg:cg-walkthrough#restricted-action-skills

      Note:  SF can essentially do what Combat Engineers can but in more
      challenging operations.
    linked_attr: Wits
    specialties:
    - Adv Breaching
    - Adv Negotiation
    - Adv Exotic
    - Adv Improvised
    - Adv Homemade
    - Adv Traps
    - Adv EVA Ordnance
    - Adv EVA Combat
    - Adv Diving Ordnance
    - Adv Diving Combat
    - Adv Robotic Operation
    - Adv Robotic Maintenance
    - Bomb Dog Training
    - Bomb Dog Handling
  - name: First Aid
    desc: |-
      Tending to people in the field.  Typically medical disciplines that do not require a
      doctorate are stronger in this skill.

      Note - Corpsmen bunk and go on missions with the marine platoons in which they are embedded.
    linked_attr: Wits
    specialties:
    - Corpsman
    - Nurse
    - Orderly
  - name: Medicine
    desc: Tending to the ill and injured.  Medical disciplines that require a doctorate
      are stronger in this skill.
    linked_attr: Wits
    specialties:
    - Doctor
    - Surgeon
    - Psychiatrist
  - name: Research
    desc: How good is your character at looking into things.  This is pretty broad
      and can be applied to research, investigation, etc.
    linked_attr: Wits
    specialties:
    - Mechanical Engineering
    - Electrical Engineering
    - Archeology
    - Theology
    - Astrophysics
    - Software
    - Hacking
    - Chemical Engineering
    - Aerospace Engineering
    - Aeronautical Engineering
    - Pharmaceutical Manufacturing
    - Materials Engineering
  - name: Design
    desc: Designing new things like prototype design (drugs, vehicles, etc).  May
      require the help of Repair specialists to get something real though.
    linked_attr: Wits
    specialties:
    - Hacking
    - Software
    - Munitions
    - Mechanical Engineering
    - Electrical Engineering
    - Chemical Engineering
    - Materials Engineering
    - Aeronautical Engineering
    - Aerospace Engineering
    - Architectural Engineering
  - name: Repair
    desc: "-| Repair and Design are both demanding fields.  Repair can also include
      manufacturing, fabrication, etc if it suits the PC's background.  Tinkerer is
      a style of Repair.  For instance, a Tinkerer might cobble together disparate
      parts.  Characters that work on weapons systems for fighters or capital ships
      are allowed to take various non-descript specialties such as Weapons Systems,
      only applying it to their area."
    linked_attr: Wits
    specialties:
    - Viper
    - Raptor
    - Predator
    - Weapons Systems
    - Communications Systems
    - Power Systems
    - Life Support Systems
    - Capital Ship Systems
    - Captial Ship Drives
    - Tinkerer
  action_skills_blurb: |-
    Action Skills represent your ability in areas deemed important for gameplay and are likely to
    get called in pertinent GMed scenes.  Action Skills are rated from 0-8, but some games limit the
    highest and lowest ratings. Only a few actually affect combat.  See
    <a href="https://aresmush.com/fs3/fs3-3/chargen.html#action-skills" target="_blank">FS3: Action Skills</a>
    for details.
