---
idle:
  arrivals_category: New Arrivals
  days_before_idle: 30
  default_contact: Admin
  idle_category: Announcements
  idle_exempt_roles:
  - admin
  - builder
  - coder
  - guest
  - staff
  - testdummy
  - tester
  idle_warn_msg: You haven't been active awhile and your character bit is in danger
    of idling out.
  monthly_reminder: It's time to run the idle sweep!
  monthly_reminder_cron:
    day:
    - 30
    hour:
    - 0
    minute:
    - 0
  monthly_reminder_title: Monthly Chores
  reminder_category: MISC
  restrict_roster: true
  roster_app_category: APP
  roster_app_template: TBD
  roster_arrival_msg: |-
    %{name} has been claimed off the roster.

    Position: %{position}

    RP Hooks:
    %{rp_hooks}
  roster_fields:
  - field: name
    width: 20
    title: Name
  - field: demographic
    width: 10
    title: Gender
    value: gender
  - field: group
    width: 17
    title: Faction
    value: Faction
  - field: group
    width: 17
    title: Position
    value: Position
  roster_welcome_msg: Welcome!  You may wish to check your %xcnotes%xn and web portal
    profile page for any notes left by the prior player.  Type %xhonstage%xn to go
    forth and RP.
  shortcuts:
    idle/add: idle/action
    roster/update: roster/add
    roster/contact: roster/add
    roster/notes: roster/note
    idle/notes: idle/note
  use_roster: true
